# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [58]:
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [59]:
print("1)\n")
print("Shape: ", df.shape)
print("Columns: ", df.columns.tolist())

1)

Shape:  (891, 12)
Columns:  ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [60]:
print("2)\n")
print("Basic Info and Summary Stats:\n")
print("--- PassengerId ---")
print("Mean:", df['PassengerId'].mean())
print("Min: ", df['PassengerId'].min())
print("Max: ", df['PassengerId'].max())
print("Std: ", df['PassengerId'].std())
print("Sum: ", df['PassengerId'].sum())
print()

print("--- Age ---")
print("Mean:", df['Age'].mean())
print("Min: ", df['Age'].min())
print("Max: ", df['Age'].max())
print("Std: ", df['Age'].std())
print("Sum: ", df['Age'].sum())
print()

print("--- SibSp ---")
print("Mean:", df['SibSp'].mean())
print("Min: ", df['SibSp'].min())
print("Max: ", df['SibSp'].max())
print("Std: ", df['SibSp'].std())
print("Sum: ", df['SibSp'].sum())
print()

print("--- Parch ---")
print("Mean:", df['Parch'].mean())
print("Min: ", df['Parch'].min())
print("Max: ", df['Parch'].max())
print("Std: ", df['Parch'].std())
print("Sum: ", df['Parch'].sum())
print()

print("--- Fare ---")
print("Mean:", df['Fare'].mean())
print("Min: ", df['Fare'].min())
print("Max: ", df['Fare'].max())
print("Std: ", df['Fare'].std())
print("Sum: ", df['Fare'].sum())

2)

Basic Info and Summary Stats:

--- PassengerId ---
Mean: 446.0
Min:  1
Max:  891
Std:  257.3538420152301
Sum:  397386

--- Age ---
Mean: 29.69911764705882
Min:  0.42
Max:  80.0
Std:  14.526497332334042
Sum:  21205.17

--- SibSp ---
Mean: 0.5230078563411896
Min:  0
Max:  8
Std:  1.1027434322934317
Sum:  466

--- Parch ---
Mean: 0.38159371492704824
Min:  0
Max:  6
Std:  0.8060572211299483
Sum:  340

--- Fare ---
Mean: 32.204207968574636
Min:  0.0
Max:  512.3292
Std:  49.6934285971809
Sum:  28693.9493

In [61]:
print("3)\n")
print("First 10 rows:\n")
print(df.head(10))

3)

First 10 rows:

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [62]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                  Heikkinen, Miss Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                          Graham, Miss Margaret Edith
888              Johnston, Miss Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [63]:
df.loc[:, ['PassengerId', 'Name', 'Sex', 'Age']]

,PassengerId,Name,Sex,Age
0,1,"Braund, Mr. Owen Harris",male,22.0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,3,"Heikkinen, Miss Laina",female,26.0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,5,"Allen, Mr. William Henry",male,35.0
...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0
887,888,"Graham, Miss Margaret Edith",female,19.0
888,889,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN
889,890,"Behr, Mr. Karl Howell",male,26.0
890,891,"Dooley, Mr. Patrick",male,32.0

In [64]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [65]:
df.iloc[2:15, 3:6]

                                                 Name     Sex   Age
2                               Heikkinen, Miss Laina  female  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                            Allen, Mr. William Henry    male  35.0
5                                    Moran, Mr. James    male   NaN
6                             McCarthy, Mr. Timothy J    male  54.0
7                       Palsson, Master Gosta Leonard    male   2.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0
10                     Sandstrom, Miss Marguerite Rut  female   4.0
11                            Bonnell, Miss Elizabeth  female  58.0
12                     Saundercock, Mr. William Henry    male  20.0
13                        Andersson, Mr. Anders Johan    male  39.0
14                Vestrom, Miss Hulda Amanda Adolfina  female  14.0

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [66]:
df[df['Age'] > 60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [67]:
df[(df['Fare'] > 100) & (df['Pclass'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [68]:
df[df['Age'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [69]:
df = df.iloc[::-1]
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [70]:
df = df.drop(columns=['Embarked'])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN

In [71]:
df = df.dropna(subset=['Age'])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [72]:
df['EuroFare'] = df['Fare'] * 0.86
df

/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/1386084273.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EuroFare'] = df['Fare'] * 0.86

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,EuroFare
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,6.665000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,25.800000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,25.800000
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,11.180000
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,25.047500
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,6.923000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,45.666000
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,6.815500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,61.303638
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,6.235000

In [73]:
df['Age'] = df['Age'] - df['Age'].mean()
df

/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/927128082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'] - df['Age'].mean()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,EuroFare
890,891,0,3,"Dooley, Mr. Patrick",male,2.300882,0,0,370376,7.7500,NaN,6.665000
889,890,1,1,"Behr, Mr. Karl Howell",male,-3.699118,0,0,111369,30.0000,C148,25.800000
887,888,1,1,"Graham, Miss Margaret Edith",female,-10.699118,0,0,112053,30.0000,B42,25.800000
886,887,0,2,"Montvila, Rev. Juozas",male,-2.699118,0,0,211536,13.0000,NaN,11.180000
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,9.300882,0,5,382652,29.1250,NaN,25.047500
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,8.0500,NaN,6.923000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,53.1000,C123,45.666000
2,3,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,7.9250,NaN,6.815500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,71.2833,C85,61.303638
0,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,6.235000

In [74]:
a = np.array([6,7])
df[['PassengerId', 'Pclass']] = df[['PassengerId', 'Pclass']] - a
df

/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/2242816550.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['PassengerId', 'Pclass']] = df[['PassengerId', 'Pclass']] - a

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,EuroFare
890,885,0,-4,"Dooley, Mr. Patrick",male,2.300882,0,0,370376,7.7500,NaN,6.665000
889,884,1,-6,"Behr, Mr. Karl Howell",male,-3.699118,0,0,111369,30.0000,C148,25.800000
887,882,1,-6,"Graham, Miss Margaret Edith",female,-10.699118,0,0,112053,30.0000,B42,25.800000
886,881,0,-5,"Montvila, Rev. Juozas",male,-2.699118,0,0,211536,13.0000,NaN,11.180000
885,880,0,-4,"Rice, Mrs. William (Margaret Norton)",female,9.300882,0,5,382652,29.1250,NaN,25.047500
...,...,...,...,...,...,...,...,...,...,...,...,...
4,-1,0,-4,"Allen, Mr. William Henry",male,5.300882,0,0,373450,8.0500,NaN,6.923000
3,-2,1,-6,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,53.1000,C123,45.666000
2,-3,1,-4,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,7.9250,NaN,6.815500
1,-4,1,-6,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,71.2833,C85,61.303638
0,-5,0,-4,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,6.235000

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [75]:
df['NumCharsName'] = df['Name'].str.len()
df

/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/2433776132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NumCharsName'] = df['Name'].str.len()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,EuroFare,NumCharsName
890,885,0,-4,"Dooley, Mr. Patrick",male,2.300882,0,0,370376,7.7500,NaN,6.665000,19
889,884,1,-6,"Behr, Mr. Karl Howell",male,-3.699118,0,0,111369,30.0000,C148,25.800000,21
887,882,1,-6,"Graham, Miss Margaret Edith",female,-10.699118,0,0,112053,30.0000,B42,25.800000,27
886,881,0,-5,"Montvila, Rev. Juozas",male,-2.699118,0,0,211536,13.0000,NaN,11.180000,21
885,880,0,-4,"Rice, Mrs. William (Margaret Norton)",female,9.300882,0,5,382652,29.1250,NaN,25.047500,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,-1,0,-4,"Allen, Mr. William Henry",male,5.300882,0,0,373450,8.0500,NaN,6.923000,24
3,-2,1,-6,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,53.1000,C123,45.666000,44
2,-3,1,-4,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,7.9250,NaN,6.815500,21
1,-4,1,-6,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,71.2833,C85,61.303638,51
0,-5,0,-4,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,6.235000,23

In [76]:
print(df['Fare'] - df['Age'])

890     5.449118
889    33.699118
887    40.699118
886    15.699118
885    19.824118
         ...
4       2.749118
3      47.799118
2      11.624118
1      62.982418
0      14.949118
Length: 714, dtype: float64

In [81]:
df['PassengerId'] = df['PassengerId'].round(1)
df['Survived'] = df['Survived'].round(1)
df['Pclass'] = df['Pclass'].round(1)
df['Age'] = df['Age'].round(1)
df['SibSp'] = df['SibSp'].round(1)
df['Parch'] = df['Parch'].round(1)
df['Fare'] = df['Fare'].round(1)
df['EuroFare'] = df['EuroFare'].round(1)
df['NumCharsName'] = df['NumCharsName'].round(1)
df

/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/3034896471.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['PassengerId'] = df['PassengerId'].round(1)
/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/3034896471.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Survived'] = df['Survived'].round(1)
/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/3034896471.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pclass'] = df['Pclass'].round(1)
/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/3034896471.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].round(1)
/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/3034896471.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SibSp'] = df['SibSp'].round(1)
/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/3034896471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Parch'] = df['Parch'].round(1)
/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/3034896471.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Fare'] = df['Fare'].round(1)
/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/3034896471.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EuroFare'] = df['EuroFare'].round(1)
/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/3034896471.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NumCharsName'] = df['NumCharsName'].round(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,EuroFare,NumCharsName
890,885,0,-4,"Dooley, Mr. Patrick",male,2.3,0,0,370376,7.8,NaN,6.7,19
889,884,1,-6,"Behr, Mr. Karl Howell",male,-3.7,0,0,111369,30.0,C148,25.8,21
887,882,1,-6,"Graham, Miss Margaret Edith",female,-10.7,0,0,112053,30.0,B42,25.8,27
886,881,0,-5,"Montvila, Rev. Juozas",male,-2.7,0,0,211536,13.0,NaN,11.2,21
885,880,0,-4,"Rice, Mrs. William (Margaret Norton)",female,9.3,0,5,382652,29.1,NaN,25.0,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,-1,0,-4,"Allen, Mr. William Henry",male,5.3,0,0,373450,8.0,NaN,6.9,24
3,-2,1,-6,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.3,1,0,113803,53.1,C123,45.7,44
2,-3,1,-4,"Heikkinen, Miss Laina",female,-3.7,0,0,STON/O2. 3101282,7.9,NaN,6.8,21
1,-4,1,-6,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.3,1,0,PC 17599,71.3,C85,61.3,51
0,-5,0,-4,"Braund, Mr. Owen Harris",male,-7.7,1,0,A/5 21171,7.2,NaN,6.2,23

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [82]:
df['Sex'] = df['Sex'].map({'male':0, 'female':1})
df

/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/932454042.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = df['Sex'].map({'male':0, 'female':1})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,EuroFare,NumCharsName
890,885,0,-4,"Dooley, Mr. Patrick",0,2.3,0,0,370376,7.8,NaN,6.7,19
889,884,1,-6,"Behr, Mr. Karl Howell",0,-3.7,0,0,111369,30.0,C148,25.8,21
887,882,1,-6,"Graham, Miss Margaret Edith",1,-10.7,0,0,112053,30.0,B42,25.8,27
886,881,0,-5,"Montvila, Rev. Juozas",0,-2.7,0,0,211536,13.0,NaN,11.2,21
885,880,0,-4,"Rice, Mrs. William (Margaret Norton)",1,9.3,0,5,382652,29.1,NaN,25.0,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,-1,0,-4,"Allen, Mr. William Henry",0,5.3,0,0,373450,8.0,NaN,6.9,24
3,-2,1,-6,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,5.3,1,0,113803,53.1,C123,45.7,44
2,-3,1,-4,"Heikkinen, Miss Laina",1,-3.7,0,0,STON/O2. 3101282,7.9,NaN,6.8,21
1,-4,1,-6,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,8.3,1,0,PC 17599,71.3,C85,61.3,51
0,-5,0,-4,"Braund, Mr. Owen Harris",0,-7.7,1,0,A/5 21171,7.2,NaN,6.2,23

In [83]:
def group_age(age):
  if age < 18:
    return 'Child'
  elif age < 60:
    return 'Adult'
  else:
    return 'Senior'
  
df['AgeGroup'] = df['Age'].apply(group_age)
df

/var/folders/2q/tc55wck90ql6px0tdfxr1yj40000gn/T/ipykernel_35561/4121719811.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['AgeGroup'] = df['Age'].apply(group_age)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,EuroFare,NumCharsName,AgeGroup
890,885,0,-4,"Dooley, Mr. Patrick",0,2.3,0,0,370376,7.8,NaN,6.7,19,Child
889,884,1,-6,"Behr, Mr. Karl Howell",0,-3.7,0,0,111369,30.0,C148,25.8,21,Child
887,882,1,-6,"Graham, Miss Margaret Edith",1,-10.7,0,0,112053,30.0,B42,25.8,27,Child
886,881,0,-5,"Montvila, Rev. Juozas",0,-2.7,0,0,211536,13.0,NaN,11.2,21,Child
885,880,0,-4,"Rice, Mrs. William (Margaret Norton)",1,9.3,0,5,382652,29.1,NaN,25.0,36,Child
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,-1,0,-4,"Allen, Mr. William Henry",0,5.3,0,0,373450,8.0,NaN,6.9,24,Child
3,-2,1,-6,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,5.3,1,0,113803,53.1,C123,45.7,44,Child
2,-3,1,-4,"Heikkinen, Miss Laina",1,-3.7,0,0,STON/O2. 3101282,7.9,NaN,6.8,21,Child
1,-4,1,-6,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,8.3,1,0,PC 17599,71.3,C85,61.3,51,Child
0,-5,0,-4,"Braund, Mr. Owen Harris",0,-7.7,1,0,A/5 21171,7.2,NaN,6.2,23,Child

### Part 8: Pure Python

I will be doing 

1. Part 2 Task 1 -- Select the names column.
2. Part 3 Task 2 -- Show rows where the fare is above 100 and the passenger was in 1st class.
3. Part 5 Task 2 -- Subtract the average age from every age value.

In [105]:
import csv, urllib.request, io

url = "https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv"

with urllib.request.urlopen(url) as f:
    content = f.read().decode('utf-8')
    reader = csv.DictReader(io.StringIO(content))   # ← use content, not f
    data = list(reader)

In [113]:
import time

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")
# get the time for the task using pandas
start = time.perf_counter()
names_pd = df['Name']
pd_time = time.perf_counter() - start

# get the time using pure python
start = time.perf_counter()
names_py = [row['Name'] for row in data]
py_time = time.perf_counter() - start

print(f"Pandas time:      {pd_time*1000:.4f} ms")
print(f"Pure Python time: {py_time*1000:.4f} ms")
print(f"First 3 names (pandas): {names_pd.head(3).tolist()}")
print(f"First 3 names (python): {names_py[:3]}")

Pandas time:      0.1684 ms
Pure Python time: 0.2600 ms
First 3 names (pandas): ['Braund, Mr. Owen Harris', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Heikkinen, Miss Laina']
First 3 names (python): ['Braund, Mr. Owen Harris', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Heikkinen, Miss Laina']

In [ ]:
# pandas
start = time.perf_counter()
result_pd = df[(df['Fare'] > 100) & (df['Pclass'] == 1)]
pd_time = time.perf_counter() - start

# python
start = time.perf_counter()
result_py = [
    row for row in data
    if float(row['Fare']) > 100 and int(row['Pclass']) == 1
]
py_time = time.perf_counter() - start

print(f"Pandas time:      {pd_time*1000:.4f} ms")
print(f"Pure Python time: {py_time*1000:.4f} ms")
print(f"Pandas matches:   {len(result_pd)}")
print(f"Python matches:   {len(result_py)}")

Pandas time:      19.7084 ms
Pure Python time: 2.4786 ms
Pandas matches:   53
Python matches:   53

In [116]:
# pandas
start = time.perf_counter()
avg_age = df['Age'].mean()                
df['AgeCentered'] = df['Age'] - avg_age     
pd_time = time.perf_counter() - start

# python
start = time.perf_counter()

# compute average, skipping missing values
ages = [float(row['Age']) for row in data if row['Age'] != '']
avg_age_py = sum(ages) / len(ages)

# subtract from each row, leaving missing as None
for row in data:
    if row['Age'] != '':
        row['AgeCentered'] = float(row['Age']) - avg_age_py
    else:
        row['AgeCentered'] = None

py_time = time.perf_counter() - start

print(f"Pandas average age:      {avg_age:.4f}")
print(f"Pure Python average:     {avg_age_py:.4f}")
print(f"Pandas time:      {pd_time*1000:.4f} ms")
print(f"Pure Python time: {py_time*1000:.4f} ms")

print(f"\nFirst 5 centered ages (pandas):")
print(df['AgeCentered'].head())
print(f"\nFirst 5 centered ages (python):")
for row in data[:5]:
    print(row['AgeCentered'])

Pandas average age:      29.6991
Pure Python average:     29.6991
Pandas time:      11.4679 ms
Pure Python time: 1.5672 ms

First 5 centered ages (pandas):
0   -7.699118
1    8.300882
2   -3.699118
3    5.300882
4    5.300882
Name: AgeCentered, dtype: float64

First 5 centered ages (python):
-7.69911764705882
8.30088235294118
-3.69911764705882
5.30088235294118
5.30088235294118